### ISSUE TITLE
UI is not loading.

### ISSUE THREAD

**Issue by raghuprathap** [hellopramith/react-redux-saga-assign-7#1]
![image](https://user-images.githubusercontent.com/3498847/44986378-28913300-afa1-11e8-926a-4058fc855b7b.png)

**Comment by pramithprakash** [comment]
Hi Raghu, This is fixed.. code was committed but push failed earlier. Thanks

**Comment by pramithprakash** [comment]
Hi Raghu, Add/Update card & Add/update list issue fixed
